spring:
 datasource:
   url: jdbc:mysql://127.0.0.1:3306/eye?charsetEncoding=UTF-8&serverTimezone=GMT&characterEncoding=utf-8
   username: root
   password: root
   platform: mysql
   driver-class-name: com.mysql.cj.jdbc.Driver
   maxActive: 20

 redis:
   host: localhost # Redis服务器地址
   database: 0 # Redis数据库索引（默认为0）
   port: 6379 # Redis服务器连接端口
   password: # Redis服务器连接密码（默认为空）
   timeout: 3000ms # 连接超时时间（毫秒）

huawei:
 url: https://111.33.175.77:18531